version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./public/converted:/usr/src/app/public/converted